# Generated by Django 3.2 on 2021-04-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kye', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
