# Generated by Django 3.2 on 2021-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kye', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
