# Generated by Django 3.2 on 2021-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kye', '0005_auto_20210421_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exceed_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
